# Generated by Django 4.1.7 on 2023-03-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_2E', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('developer', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=64)),
            ],
        ),
    ]
