# Generated by Django 4.1.7 on 2023-03-11 18:38

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_2E', '0002_games'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Games',
        ),
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('user_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
