# Generated by Django 4.1.7 on 2023-03-12 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_3E', '0004_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='disc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson_3E.games'),
        ),
    ]
