# Generated by Django 4.1.7 on 2023-02-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('on_shop', models.BooleanField()),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('date1', models.DateField()),
                ('date2', models.DateTimeField()),
                ('date3', models.DurationField()),
                ('email', models.EmailField(max_length=254)),
                ('file', models.FileField(upload_to='')),
                ('weight', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=2)),
                ('site', models.URLField()),
                ('uuid', models.UUIDField()),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
    ]
