# Generated by Django 4.1.7 on 2023-02-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_5', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wrape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('name', models.CharField(max_length=30)),
                ('color', models.ManyToManyField(to='lesson_5.book', verbose_name='this wrape has the same color of this books')),
            ],
        ),
    ]
