# Generated by Django 4.1.7 on 2023-02-25 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_5', '0003_alter_book_count_alter_book_date1_alter_book_date2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='date1',
        ),
        migrations.RemoveField(
            model_name='book',
            name='date2',
        ),
        migrations.RemoveField(
            model_name='book',
            name='date3',
        ),
    ]
