# Generated by Django 4.1.7 on 2023-02-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_5', '0005_remove_book_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=5, default='', max_digits=5),
        ),
    ]
