# Generated by Django 4.1.7 on 2023-02-25 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_5', '0006_alter_book_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
    ]
