# Generated by Django 4.1.7 on 2023-02-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_5', '0009_alter_book_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrape',
            name='color',
            field=models.ManyToManyField(default='', to='lesson_5.book', verbose_name='this wrape has the same color of this books'),
        ),
    ]
