# Generated by Django 4.1.7 on 2023-02-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_5', '0010_alter_wrape_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='on_shop',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='site',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='wrape',
            name='color',
            field=models.ManyToManyField(to='lesson_5.book', verbose_name='this wrape has the same color of this books'),
        ),
        migrations.AlterField(
            model_name='wrape',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wrape',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
