# Generated by Django 4.1.7 on 2023-02-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_5', '0012_remove_book_description_remove_book_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='test',
            field=models.CharField(default=None, max_length=43),
        ),
    ]
