# Generated by Django 4.1.7 on 2023-02-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_5', '0017_alter_book_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='test',
            field=models.CharField(default=123, max_length=43),
            preserve_default=False,
        ),
    ]
