# Generated by Django 4.1.7 on 2023-02-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonTask3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('biography', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('stars', models.FloatField()),
            ],
        ),
    ]
