# Generated by Django 4.1.7 on 2023-02-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_7', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPersonTask3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('biography', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('stars', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='PersonTask3',
        ),
    ]
