# Generated by Django 4.1.7 on 2023-03-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('developer', models.CharField(max_length=244)),
                ('platform', models.CharField(max_length=123)),
            ],
        ),
    ]
