# Generated by Django 4.1.7 on 2023-03-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_4E', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='color',
            field=models.BooleanField(default=False),
        ),
    ]
