# Generated by Django 4.1.7 on 2023-03-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_10', '0002_gamesbase_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cityes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
            ],
        ),
    ]
