# Generated by Django 4.1.7 on 2023-03-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelForLesson8Task1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('platform', models.CharField(max_length=64)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=64)),
                ('developer', models.CharField(max_length=64)),
                ('sales1', models.FloatField()),
                ('sales2', models.FloatField()),
                ('sales3', models.FloatField()),
                ('sales4', models.FloatField()),
                ('sales5', models.FloatField()),
            ],
        ),
    ]
