# Generated by Django 4.1.7 on 2023-03-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_8', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelforlesson8task1',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
