# Generated by Django 4.1.7 on 2023-03-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_8', '0002_alter_modelforlesson8task1_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelforlesson8task1',
            name='name',
            field=models.CharField(max_length=640),
        ),
    ]
