# Generated by Django 4.1.7 on 2023-03-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_8', '0003_alter_modelforlesson8task1_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelForPersonsLesson8Task2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ModelForProfessionsLesson8Task2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=64)),
                ('salary', models.IntegerField()),
                ('persons', models.ManyToManyField(to='lesson_8.modelforpersonslesson8task2')),
            ],
        ),
    ]
